### ISSUE TITLE
Add Install Guide to README

### ISSUE THREAD

**Issue by joshpalan** [onlykey/onlykey.github.io#12]
There is no section on how to install and run this on a local environment. I'd love to hack on this but I don't know where to start. I'd love to see some sort of guide to getting running on a local server.

**Comment by onlykey** [comment]
@joshpalan The issue is that FIDO2 requires https and for security reasons we only allow the domain apps.crp.to. So in order to test this locally you would need an OnlyKey with custom firmware and a way to locally host https.

**Comment by joshpalan** [comment]
Understood! Thanks for the info, I've had my OnlyKey for a little over a year now and I still love it. I'm also glad to see development again towards all of the OnlyKey apps. I only wish I could get lights on my OK when using it in a USB3 port without having to also use a USB hub of some kind, but I'm not sure if that's possible to fix in software. Thanks again, I'll close this out.
