### ISSUE TITLE
Need to send session key back to kbpgp

### ISSUE THREAD

**Issue by onlykey** [onlykey/onlykey.github.io#8]
The correct session key is now decrypted by OnlyKey
![image](https://user-images.githubusercontent.com/18121756/27450975-80c767be-575b-11e7-90da-33aacba7bbe3.png)

Now we need to do the magic to import this session key back to the function that needs it to decrypt the data - 
![image](https://user-images.githubusercontent.com/18121756/27449714-51d75170-5757-11e7-9c58-93076a8af172.png)

This will likely result in errors as kbpgp is designed to have the private key, may need to load a test key so kbpgp thinks it has the private key and then just remove any errors like if the test key fingerprint does not match the message.

**Comment by petoem** [comment]
While looking at the kbpgp code, I found this function: 
https://github.com/keybase/kbpgp/blob/master/lib/openpgp/processor.js#L368

Here is the IcedCoffeeScript version:  https://github.com/keybase/kbpgp/blob/master/src/openpgp/processor.iced#L197

Maybe this helps.
